# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.services.utils.string:
        class: AppBundle\Service\Utils\StringUtils
        arguments: []

    app.services.listener.event:
            class: AppBundle\Service\Listener\EventListener
            arguments:  [ '@app.services.utils.string' ]
            tags:
                - { name: doctrine.orm.entity_listener }
